on:
  pull_request_review:
    types: [submitted, edited, dismissed]
    
jobs:
  submitted-review:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'submitted' }}
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Shadow Review submission
        run: |
          echo "code for shawdowing newly created review should be here"
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const pullRequestNumber = context.payload.pull_request.number;
            const branchName = 'from_external_refs/pull/' +  pullRequestNumber + '/head';
            
            console.log('branch Name', branchName);
            
            const prs = await github.pulls.list({
              owner: 'sample-organisation',
              repo: 'internal',
              base: 'main',
              head: 'sample-organisation:' + branchName,
            });
            
            if (prs.status != 200) {
              core.setFailed('API request to get pull requests returned non-success status code ' + prs.status);
              return;
            } 
            
            if (prs.data.length < 1) {
              core.setFailed('No PR found');
              return;    
            }
            
            const pr = prs.data[0];
            console.log('pr');
            console.log(JSON.stringify(pr, null, 4));

  edited-review:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'edited' }}
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Shadow Comment Edits
        run: |
          echo "code for shawdowing edits to a reviews should be here"
          
          
  dismissed-review:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'dismissed' }}
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Shadow Review dismiss
        run: |
          echo "code for shawdowing review deletes should be here"
