on:
  pull_request_review_comment:
    types: [created, edited, deleted]
    
jobs:
  created-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'created' }}
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Shadow Comment Creation
        run: |
          echo "code for shawdowing newly created comment should be here"

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const pullRequestNumber = context.payload.pull_request.number;
            const branchName = 'from_external_refs/pull/' +  pullRequestNumber + '/head';
            
            console.log('branch Name', branchName);
            
            const prs = await github.pulls.list({
              owner: 'sample-organisation',
              repo: 'internal',
              base: 'main',
              head: 'sample-organisation:' + branchName,
            });
            
            if (prs.length < 1) {
              core.setFailed('No PR found');
              return;    
            }
            
            const pr = prs[0];
            console.log('pr number', pr.number);

  edited-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'edited' }}
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Shadow Comment Edits
        run: |
          echo "code for shawdowing edits to a comment should be here"
          
          
  deleted-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'deleted' }}
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Shadow Comment Deletion
        run: |
          echo "code for shawdowing comment deletes should be here"
