on:
  pull_request_review_comment:
    types: [created, edited, deleted]
    
jobs:
  created-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'created' }}
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Shadow Comment Creation
        run: |
          echo "code for shawdowing newly created comment should be here"


  edited-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'edited' }}
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Shadow Comment Edits
        run: |
          echo "code for shawdowing edits to a comment should be here"
          
          
  deleted-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'deleted' }}
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Shadow Comment Deletion
        run: |
          echo "code for shawdowing comment deletes should be here"
